services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379'

  wiremock:
    image: "local/wiremock:3.3.1-1"
    build:
      context: ./mock-services
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
