services:
  api-gateway:
    image: local/idempotent-api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - '8080:8080'

  # infra
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  wiremock:
    image: "local/wiremock:3.3.1-1"
    build:
      context: ./mock-api
      dockerfile: Dockerfile
    ports:
      - '8081:8080'

  # monitoring
  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - '9090:9090'
    volumes:
      - ./infra/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.4.12
    ports:
      - '3000:3000'
    volumes:
      - ./infra/observability/grafana/provisioning:/etc/grafana/provisioning
