spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

api-gateway:
  routes:
    service1:
      source:
        path: /action1
      target:
        uri: http://localhost:8081
        path: /service1/action1
