{
 "title": "API Gateway - Lettuce Prometheus Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "_filter_instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "HTTP latency vs Redis latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "lettuce_command_completion_seconds_max{command=~\"GET|SETEX\", instance=\"$_filter_instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_client_requests_seconds_max",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_max{uri!=\"/actuator/prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Completion Max (s)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "lettuce_command_completion_seconds_max{command=~\"SETEX|GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SETX - FirstResponse Max vs Completion Max (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "lettuce_command_firstresponse_seconds_max{command=\"SETEX\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lettuce_command_completion_seconds_max{command=\"SETEX\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET - FirstResponse Max vs Completion Max (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "lettuce_command_completion_seconds_max{command=\"GET\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lettuce_command_firstresponse_seconds_max{command=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lettuce - Command Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "lettuce_command_completion_seconds_count{command=~\"GET|SETEX\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lettuce_command_firstresponse_seconds_count{command=~\"GET|SETEX\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}